name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Update version
      run: |
        sed -i '' "s/version = \".*\"/version = \"${{ github.event.inputs.version }}\"/" build.gradle.kts
    
    - name: Build release
      run: ./gradlew build --no-daemon
    
    - name: Run tests
      run: ./gradlew test --no-daemon
    
    - name: Create tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Release version ${{ github.event.inputs.version }}"
        git tag -a "v${{ github.event.inputs.version }}" -m "Release version ${{ github.event.inputs.version }}"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        tags: true
    
    - name: Publish to Maven Central
      run: ./gradlew publish --no-daemon
      env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ github.event.inputs.version }}"
        release_name: "Release v${{ github.event.inputs.version }}"
        body: |
          ## StateHolder KMP v${{ github.event.inputs.version }}
          
          ### Published Modules
          - `io.github.rentoyokawa:stateholder-annotations:${{ github.event.inputs.version }}`
          - `io.github.rentoyokawa:stateholder-core:${{ github.event.inputs.version }}`
          - `io.github.rentoyokawa:stateholder-viewmodel-koin:${{ github.event.inputs.version }}`
          - `io.github.rentoyokawa:stateholder-processor-koin:${{ github.event.inputs.version }}`
          
          ### Usage
          ```kotlin
          dependencies {
              implementation("io.github.rentoyokawa:stateholder-core:${{ github.event.inputs.version }}")
              implementation("io.github.rentoyokawa:stateholder-viewmodel-koin:${{ github.event.inputs.version }}")
              ksp("io.github.rentoyokawa:stateholder-processor-koin:${{ github.event.inputs.version }}")
          }
          ```
        draft: false
        prerelease: ${{ contains(github.event.inputs.version, 'alpha') || contains(github.event.inputs.version, 'beta') || contains(github.event.inputs.version, 'rc') }}